config/routes.rb
Tuspark::Application.routes.draw do
  resources :pois
  resources :companies


  resources :contents do
    member do
      get "subscribe"
      get "unsubscribe"
      get "invitation"
    end
  end

  get '/updater', :to => 'home#updater'

  get "/company/get", :to => "companies#home"
  get "/download", :to => "home#dl"

  resources :categories
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  root :to => "home#index"
  devise_for :users, :controllers =>
  		{
  			sessions: 'sessions',
  			registrations: 'registrations'
  		}
  devise_scope :user do
    get "/users/me", :to => "users#me"
    get "/users/add_favorite", :to => "users#add_favorite"
    get "/users/delete_favorite", :to => "users#delete_favorite"
    get "/users/list_favorites", :to => "users#list_favorites"
    get "/users/favorites", :to => "users#favorites"
  end
end

app/models/poi.rb
class Poi < ActiveRecord::Base
  attr_accessible :address, :description, :latitude, :longitude, :name
  attr_accessible :image
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/poi_image_missing.png"
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/controllers/pois_controller.rb
class PoisController < InheritedResources::Base

    def index

        @pois = Poi.all
        @center = {
            :latitude => Poi.average('latitude').to_f,
            :longitude => Poi.average('longitude').to_f
        }

    end

end

app/helpers/pois_helper.rb
module PoisHelper
end

app/views/pois/_form.html.erb
<%= simple_form_for(@poi) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pois/edit.html.erb
<h1>Editing poi</h1>

<%= render 'form' %>

<%= link_to 'Show', @poi %> |
<%= link_to 'Back', pois_path %>

app/views/pois/index.html.erb
<h1>Listing pois</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pois.each do |poi| %>
  <tr>
    <td><%= poi.name %></td>
    <td><%= poi.address %></td>
    <td><%= poi.latitude %></td>
    <td><%= poi.longitude %></td>
    <td><%= poi.description %></td>
    <td><%= link_to 'Show', poi %></td>
    <td><%= link_to 'Edit', edit_poi_path(poi) %></td>
    <td><%= link_to 'Destroy', poi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Poi', new_poi_path %>

app/views/pois/new.html.erb
<h1>New poi</h1>

<%= render 'form' %>

<%= link_to 'Back', pois_path %>

app/views/pois/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @poi.name %>
</p>

<p>
  <b>Address:</b>
  <%= @poi.address %>
</p>

<p>
  <b>Latitude:</b>
  <%= @poi.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @poi.longitude %>
</p>

<p>
  <b>Description:</b>
  <%= @poi.description %>
</p>


<%= link_to 'Edit', edit_poi_path(@poi) %> |
<%= link_to 'Back', pois_path %>